name: Get AWS Secrets into workflow

on: [push]

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Assume Workflow Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-north-1
          role-to-assume: arn:aws:iam::008971664413:role/Github_Actions
          role-duration-seconds: 1200
          role-skip-session-tagging: true

      - name: Get secret using AWS CLI
        run: |
          aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:eu-north-1:008971664413:secret:aem-creds-IsnUVY --query 'SecretString' --output text

      - name: Print secret to logs
        run: |
          SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:eu-north-1:008971664413:secret:aem-creds-IsnUVY --query 'SecretString' --output text)
          echo "Raw secret output: $SECRET_VALUE"
